final/urls.py
from django.contrib import admin
from django.urls import path,include

from onedaytwogether import views as onedaytwogether
from onedaytwogether.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onedaytwogether/', include('onedaytwogether.urls')),
]

onedaytwogether/urls.py
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from django.conf import settings
from onedaytwogether import views as onedaytwogether_view
from . import views
from onedaytwogether.views import *
app_name = 'onedaytwogether'
urlpatterns = [
    # url('^home/$', staff_view.home_page, name='home'),
    re_path('^Home/$', onedaytwogether_view.HomeView.as_view(), name='index'),
    re_path('^Destination/$', onedaytwogether_view.DestinationView.as_view(), name='Destination'),
    re_path('^Shop/$', onedaytwogether_view.ShopView.as_view(), name='shop'),
    re_path('^Contact/$', onedaytwogether_view.ContactView.as_view(), name='contact'),
    re_path('^Aboutus/$', onedaytwogether_view.AboutusView.as_view(), name='Aboutus')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onedaytwogether/models.py
from django.db import models

# Create your models here.

onedaytwogether/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView 
from django.views import generic
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class HomeView(View):
    template_name = 'index.html'
    
    def get(self, request):
        return render(request, self.template_name)
class DestinationView(View):
    template_name = 'Destination.html'
    
    def get(self, request):
        return render(request, self.template_name)
class ShopView(View):
    template_name = 'shop.html'
    
    def get(self, request):
        return render(request, self.template_name)
class ContactView(View):
    template_name = 'contact.html'
    
    def get(self, request):
        return render(request, self.template_name)
class AboutusView(View):
    template_name = 'aboutus.html'
    
    def get(self, request):
        return render(request, self.template_name)
  

final/templates/Destination.html
{% extends 'header.html' %}
{%load static%}
{% block main_body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/Destination.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>

    <!-- Head -->
    <div class="header">
        <center>
            <h3>Find yourself outside. </h3>
            <p>Discover a wonderful please in Cambodia</p>
            <form method="get" action="Destination-search.html">
                <div class="menu-search">

                    <div>
                        <i class="fa-solid fa-location-dot"></i>
                        <input type="text" placeholder="Search Destinations" name="search" id="">
                    </div>
                    <div>
                        <input style="color: white;" type="submit" value="Search" name="" id="Search-button">
                    </div>
                </div>
            </form>
        </center>
    </div>


    <div class="text-body">
        <h3>Camping Trip: </h3>

        <h3>Where to Go: </h3>
        <p>
            <br>
        </p>
        <br>
    </div>

    <div class="the-destination" style="width:100%">
        <!-- first destination -->
        <div class="knongpsar">
            <a href="FirstDestination.html"><img src="" alt=""></a>
            <div class="knongpsar-info">
                <b>
                    <h4>

                    </h4>
                </b>
                <b>

                </b><br><br>
                <p>

                </p>
                <p>--------</p>

                <p>Team :

                </p>
                <p>Phone Number :

                </p>
                <p>Email :

                </p>
                <p>Service :

                </p>
                <p>Date :

                </p>

                <a href="contact.html"><input type="button" value="Booking" name="" id=""></a>
            </div>
        </div>
        <br>


    </div>

</body>
{% endblock main_body %}

final/templates/FirstDestination.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/FirstDestination.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    <div class="pkpinfo">
        <div id="location">
            <a href="">Cambodia</a> > <a href="">Kompong Speu</a>
        </div>
        <h1>Phnom Khnong Phsar</h1>
        <div class="view">
            <i class="fa-regular fa-thumbs-up">99%</i>
            <a href="">240 reviews</a>
        </div>
        <div class="innp">
            <input class="check-availablility" type="button" value="Check availablility" name="" id="">
            <div class="inpsh">
                <i class="fa-solid fa-arrow-up-from-bracket"></i>
                <input type="button" value="Share" name="" id="">
            </div>
        </div>
        <div class="pkpimg">
            <div class="leftside">
                <img src="img/pt.jpg" alt="">
            </div>
            <div class="rightside">
                <img class="f" src="img/p.jpg" alt="">
                <img class="s" src="img/p9.jpg" alt="">
            </div>
        </div>
        <div class="information">
            <div class="p1">
                <b>
                    <h4> <i class="fa-solid fa-location-dot"></i>Phnom Khnong Phsar is located in Tangbong village,
                        Rolak Kang Cheung area, <br>&nbsp; Ta Sal commune, Oral district, Kampong Speu province.
                    </h4>
                </b>
                <p style="margin-bottom: 25px;">About Khnmong Phsar: Khnong Phsar is a junction of three comers that
                    connects three <br>provinces: Koh Kong, Kampong Speu and Pursat <br>Khnong Phsart is an area
                    rich in dense forests, high valleys,beautiful pine fields and <br> rich in rare species of
                    wildlife, In the morning we should travel to the back of the marke.</p>
                <a href="">Show more ></a>
            </div>
            <div class="p2">
                <ul>
                    <b>Activities</b>
                    <li><a href="">Riding</a></li>
                    <li><a href="">Camping</a></li>
                    <li><a href="">Fishing</a></li>
                    <li style="text-decoration: underline !important;"><a href="">Show more ></a></li>
                </ul>
            </div>
            <div class="p3">
                <ul>
                    <b>Natural Features</b>
                    <li><a href="">Forest</a></li>
                    <li><a href="">Lake</a></li>
                    <li><a href="">Mountainous</a></li>
                </ul>
            </div>
        </div>

    </div>
    <h1 style="margin-bottom: 30px;">Book <span style="color: #007180;">Now</span></h1>
    <div class="contact" style="display: flex;">
        <div style="display: flex; margin-right: 40px;">
            <i class="fa-solid fa-phone-volume"></i>
            <p style="color: #007180;">(+8565) 456 789</p>
        </div>
        <div style="display: flex;">
            <i class="fa-solid fa-envelope-open-text"></i>
            <p style="color: #007180;">1day2gethercamp@gmail.com</p>
        </div>
    </div>

    </div>

</body>

final/templates/aboutus.html
{% extends 'header.html' %}
{%load static%}
{% block main_body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/aboutus.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="cointainer-fluid">
        <!-- Head -->
        <div class="header">
            <center>
                <h3>About 1DAY2GETHER </h3>
            </center>
        </div>
        <div class="text-body">
            <h3> </h3>
        </div>
        <div class="the-destination" style="width:90%;margin-left:70px">
            <div class="knongpsar">
                <div class="knongpsar-info">
                    <b>
                        <h4>
                            <u>What are we?</u>
                        </h4>
                    </b>
                    <b>WE ARE 1DAY2GETHER</b><br><br>
                    <p>We are a group of student that have a love camping and the nature and we want to help everyone
                        connect to the nature.</p>
                </div>

                <img src="{% static 'img/1.JPG' %}" alt="">

            </div>

            <div class="knongpsar">
                <img src="{% static 'img/2.JPG' %}" alt="">
                <div class="knongpsar-info">
                    <b>
                        <h4><u>What we do?</u></h4>
                    </b>
                    <b>WE ARE 1DAY2GETHER
                    </b><br><br>
                    <p>Help you prepare for your camping experience! We offer you a place to camp, as well as a wide
                        selection of camping supplies to make your experience enjoyable and comfortable.</p>
                </div>
            </div>

            <div class="knongpsar">
                <div class="knongpsar-info">
                    <b>
                        <h4><u>Our Purpose</u></h4>
                    </b>
                    <b>WE ARE 1DAY2GETHER
                    </b><br><br>
                    <p>The purpose of the trip is to connect people for nature lovers to get to know each other better,
                        to build a memorable relationship in the same day together and expand the nature tourism to a
                        wider range.</p>
                </div>

                <img src="{% static 'img/3.JPG' %}" alt="">

            </div>

        </div>
    </div>


</body>
{% endblock main_body %}

final/templates/contact.html
{% extends 'header.html' %}
{% load static %}
{% block main_body %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Contact</title>
	<link rel="stylesheet" href="{% static 'css/contact.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
		integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
		integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

	<br>
	<h1 style="text-align: center;font-size: 300%;">Contact</h1>
	<div class="Greenblock">

	</div>
	<br>
	<br>
	<div class="contact">
		<form method="post">
			<div class="abovetext"><br>
				<p>Get in <span style="color:#124747">touch</span></p>

			</div>
			<div class="input">
				<input id="text" type="text" name="Name" placeholder="Name"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:80%;"><br><br>
				<input id="text" type="text" name="Street" placeholder="Street"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:80%;margin-top:2%"><br><br>
				<input id="text" type="text" name="City" placeholder="City"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:45%;margin-top:2%">
				<input id="text" type="text" name="Posscode" placeholder="Posscode"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:29%;margin-top:-25px;margin-left:25px"><br><br>
				<input id="text" type="text" name="ContactNumber" placeholder="Contact Number"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:80%;margin-top:2%"><br><br>
				<input id="text" type="text" name="email" placeholder="Email"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:80%;margin-top:2%"><br><br>
				<select class="form-control" name="Location" style="width:80%">

					<option value=""></option>

				</select>
				<input id="text" type="text" name="lettalk" placeholder="Let talk"
					style="font-size:medium;border-top: none;border-left:none;border-right:none;width:80%;margin-top:2%"><br><br>

				<br>
				<br>
				<br>

				<input id="button" type="submit" value="Submit"
					style="margin-top:2%;font-size:large;border:none;background: #0982FE;width:80%;color:white;height: 50px;border-radius: 10px"><br>
			</div>


			<div class="phone">
				<br>
				<img src="{% static 'image/Screenshot 203-04-18 153933.png' %}"
					style="width: 28px;height: 28px;margin-left:-70%">
				<p class="phonetext">
					Phone <br>(+855) 456 7890</p>
			</div>
			<div class="Email" style="">
				<br>
				<img src="{% static 'image/email.png' %}" style="width: 28px;height: 28px;margin-left:-90%">
				<p class="phonetext">
					Email <br>1day2gethercamp@gmail.com</p>
			</div>

		</form>

	</div>

</body>

</html>
<div style="width:100%">

</div>
{% endblock main_body %}

final/templates/header.html
{% load static %}
{% load %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/Homepage.css'%}">
    <link rel="stylesheet" href="{%static 'css/profile_user.css'%}">
    <link href="{%static 'css/shop.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<style>
    table {
        table-layout: fixed;
        width: 100%;
    }

    td {
        width: 33.33%;
    }
</style>

<body>
    <div class="cointainer-fluid">
        <!-- menu -->
        <div class="menu">

            <!-- logo -->
            <div class="menu-logo">
                <img src="{%static 'image/logo.png' %}" alt="">
            </div>

            <!-- menu link -->
            <div class="menu-link" id="menu-link-ul">
                <ul>
                    <li><a href="{% url 'onedaytwogether:index' %}">Home</a></li>
                    <li><a href="{% url 'onedaytwogether:Destination' %}">Destination</a></li>
                    <li><a href="{% url 'onedaytwogether:shop' %}">Shop</a></li>
                    <li><a href="{% url 'onedaytwogether:Aboutus' %}">About Us</a></li>
                    <li><a href="{% url 'onedaytwogether:contact' %}">Contact</a></li>
                </ul>
            </div>

            <!-- menu icon -->
            <div class="menu-icon">
                <a onclick="toggle()">
                    <i class="fa-solid fa-bars" id="bar"></i>
                </a>
                <a onclick="toggleUSER()">
                    <i class="fa-regular fa-user" id="abar"></i>
                </a>

            </div>

            <div class="User" id="User" style="height:100px;margin-top:150px;margin-left:89%">
                <div class="button-btn">
                    <a href="login.html"><button>Login</button></a>
                    <a href="signup.html"><button>Sign up</button></a>
                </div>
            </div>


            <div class="User" id="User" style="height:auto;margin-top:250px;margin-left:88%">
                <img class="" src="" alt="">
                <h5></h5>
                <p></p>
                <hr>
                <p>Purchase History</p>
                <div style="text-align:center;">
                    <table>
                        <tr>
                            <th>Product</th>
                            <th>Amount</th>
                            <th>Price</th>
                        </tr>

                        <tr>
                            <td style="font-size: 13px;"></td>
                            <td></td>
                            <td></td>
                        </tr>

                    </table>
                </div>
                <hr>

                <div class="button-btn">
                    <a href="Homepageadmin.html"><button>Admin</button></a>
                    <a href="logout.html"><button>Sign out</button></a>
                </div>

                <div class="button-btn">
                    <a href="logout.html"><button>Sign out</button></a>
                </div>

            </div>


        </div>

        <script>
            function toggle() {
                let bar = document.getElementById("menu-link-ul");
                if (bar.style.display === "block") {
                    bar.style.display = "none";
                } else {
                    bar.style.display = "block";
                }
            }

            function toggleUSER() {
                let abar = document.getElementById("User");
                if (abar.style.display === "none") {
                    abar.style.display = "block";
                } else {
                    abar.style.display = "none";
                }
            }
        </script>
        <div>
            {% block main_body %}{% endblock main_body %}
        </div>

        <style>
            #col-3 {
                width: 25%;
            }

            #row::after {
                content: "";
                clear: both;
                display: table;
            }

            [class*="col-"] {
                float: left;
                padding: 0px;
            }

            #footer {
                background-color: rgb(244, 232, 5);
                color: rgb(0, 0, 0);
                padding: 0px;
                height: auto;
            }

            #h2 {
                font-style: bold;
            }
        </style>
        <!--footer-->
        <div class="footer" style="width:100% ; background-color:yellow">
            <div class="row" style="width:100% ;">
                <div class="col-4" align="center">
                    <p style="font-size: larger;">Location</p>
                    <h2 style="font-size: medium;">Khan 7 Makara, Phnom Penh</h2>
                </div>
                <div class="col-4" align="center">
                    <p style="font-size: larger;">Email</p>
                    <h2 style="font-size: medium;">1Day2Gether@gmail.com</h2>
                </div>
                <div class="col-4" align="center">
                    <p style="font-size: larger;">Contact Number</p>
                    <h2 style="font-size: medium;">(+855) 456 7890</h2>
                </div>
            </div>
            <div align=center>
                <a href="https://www.facebook.com/groups/178330630927426/"><svg xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 448 512"
                        width=30px><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                        <path
                            d="M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z" />
                    </svg></a>
                <a href="https://www.youtube.com/@ChavmeanupSamedy"><svg xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 576 512"
                        width=30px><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                        <path
                            d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z" />
                    </svg></a>
                <a href="https://www.instagram.com/campingpark_/"><svg xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 448 512"
                        width=30px><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                        <path
                            d="M224,202.66A53.34,53.34,0,1,0,277.36,256,53.38,53.38,0,0,0,224,202.66Zm124.71-41a54,54,0,0,0-30.41-30.41c-21-8.29-71-6.43-94.3-6.43s-73.25-1.93-94.31,6.43a54,54,0,0,0-30.41,30.41c-8.28,21-6.43,71.05-6.43,94.33S91,329.26,99.32,350.33a54,54,0,0,0,30.41,30.41c21,8.29,71,6.43,94.31,6.43s73.24,1.93,94.3-6.43a54,54,0,0,0,30.41-30.41c8.35-21,6.43-71.05,6.43-94.33S357.1,182.74,348.75,161.67ZM224,338a82,82,0,1,1,82-82A81.9,81.9,0,0,1,224,338Zm85.38-148.3a19.14,19.14,0,1,1,19.13-19.14A19.1,19.1,0,0,1,309.42,189.74ZM400,32H48A48,48,0,0,0,0,80V432a48,48,0,0,0,48,48H400a48,48,0,0,0,48-48V80A48,48,0,0,0,400,32ZM382.88,322c-1.29,25.63-7.14,48.34-25.85,67s-41.4,24.63-67,25.85c-26.41,1.49-105.59,1.49-132,0-25.63-1.29-48.26-7.15-67-25.85s-24.63-41.42-25.85-67c-1.49-26.42-1.49-105.61,0-132,1.29-25.63,7.07-48.34,25.85-67s41.47-24.56,67-25.78c26.41-1.49,105.59-1.49,132,0,25.63,1.29,48.33,7.15,67,25.85s24.63,41.42,25.85,67.05C384.37,216.44,384.37,295.56,382.88,322Z" />
                    </svg></a>
                <a href="https://t.me/+iHSuh6seoeAzZjY1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"
                        width=30px><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                        <path
                            d="M248,8C111.033,8,0,119.033,0,256S111.033,504,248,504,496,392.967,496,256,384.967,8,248,8ZM362.952,176.66c-3.732,39.215-19.881,134.378-28.1,178.3-3.476,18.584-10.322,24.816-16.948,25.425-14.4,1.326-25.338-9.517-39.287-18.661-21.827-14.308-34.158-23.215-55.346-37.177-24.485-16.135-8.612-25,5.342-39.5,3.652-3.793,67.107-61.51,68.335-66.746.153-.655.3-3.1-1.154-4.384s-3.59-.849-5.135-.5q-3.283.746-104.608,69.142-14.845,10.194-26.894,9.934c-8.855-.191-25.888-5.006-38.551-9.123-15.531-5.048-27.875-7.717-26.8-16.291q.84-6.7,18.45-13.7,108.446-47.248,144.628-62.3c68.872-28.647,83.183-33.623,92.511-33.789,2.052-.034,6.639.474,9.61,2.885a10.452,10.452,0,0,1,3.53,6.716A43.765,43.765,0,0,1,362.952,176.66Z" />
                    </svg></a>
            </div>
        </div>

</body>

final/templates/index.html
{% extends 'header.html' %}
{%load static%}
{% block main_body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/Homepage.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>


    <!-- head -->
    <div class="header">
        <div class="banner">
            <img src="{%static 'Camping/Page img/photo_1_2023-03-12_15-22-03.jpg'%}" alt="">
            <center>
                <h1>

                </h1>
                <a href="{% url 'onedaytwogether:contact' %}"><input type="button" name="" value="Book Now" id=""></a>
            </center>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <div class="info">
        <div class="info-text">
            <center>
                <h1>
                    Camping In <br> Cambodia Through <br> <span style="color: #FFF505;">1</span>Day2<span
                        style="color: #FFF505;">G</span>ether
                </h1><br><br>
                <p>We offer you a place and a wide of camping <br> supplies to make your selection enjoyable <br>
                    and make a perfect connection between you <br> and nature. </p><br><br>
                <p>
                    Check out our different varieties camping <br> supplies and our services!</p>
            </center>
        </div>
        <div class="info-img">
            <img class="classA" src="{%static 'Camping\Page img\photo_2_2023-03-12_15-22-03.jpg'%}" alt="">
            <img class="classB" src="{%static 'Camping\Page img\photo_3_2023-03-12_15-22-03.jpg'%}" alt="">
        </div>
    </div>
    <div class="destination">
        <div class="khnong-phsar">
            <a href="FirstDestination.html"><img src="" alt=""></a>
            <h1>

            </h1>
        </div>
        <div class="khnong-phsar">
            <img src="" alt="">
            <h1>

            </h1>
        </div>
        <div class="khnong-phsar">
            <img src="" alt="">
            <h1>

            </h1>
        </div>
    </div>
    <div class="shop">
        <div class="shop-img">
            <img src="" alt="">
        </div>
        <div class="shop-info">
            <h1>Shop for your</h1>
            <h2>supplies!</h2>
            <p>We offer varieties of camping <br> packages for you to choose from, <br> depending on lyour dream
                <br> destination !
            </p><br><br>
            <a href="shop.html"><input type="button" value="        Go to shop" name="btn-shop" id=""></a>
        </div>
    </div>
    <div class="footer" style="background-color: #FFF505;">
        <div class="info-footer">
            <img src="" alt="">
            <p>

            </p>
        </div>

    </div>
    <div style="width: 100%;">

    </div>

</body>
{% endblock main_body %}